[build]
  publish = "client/dist"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# Redirect API calls to Netlify Functions (not needed for static site)
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 404

# SPA fallback - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
